-- รันครั้งเดียวใน Supabase SQL Editor เพื่อสร้างตารางเก็บ log การสุ่มแจก Super Token
create table if not exists token_gacha_log (
  id bigint generated by default as identity primary key,
  session_id bigint not null,
  project_name text not null,
  student_id text not null,
  amount int not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists idx_token_gacha_log_session on token_gacha_log (session_id);
create index if not exists idx_token_gacha_log_project on token_gacha_log (project_name);

alter table token_gacha_log enable row level security;

-- อนุญาตให้ anon key (ที่แอปนี้ใช้) อ่าน/เขียน log ได้ เหมือนตาราง students ที่ใช้อยู่แล้ว
create policy "Allow anon read token_gacha_log" on token_gacha_log for select using (true);
create policy "Allow anon insert token_gacha_log" on token_gacha_log for insert with check (true);
